version: '3'
services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /app/nginx-proxy-manager/data:/data
      - /app/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    image: 'jc21/nginx-proxy-manager:latest'