version: '3.8'
services:
  firefox:
    image: jlesage/firefox
    container_name: docker-in-firefox
    environment:
      - LANG=ko_KR.UTF-8
    ports:
      - "5800:5800"
    volumes:
      - "/app/firefox:/config:rw"
    restart: unless-stopped