version: "3.9"

services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: always
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace  # named volume 사용

volumes:
  cloudbeaver_data:
    driver: local
    driver_opts:
      type: none
      device: /volume1/docker/cloudbeaver  # 호스트 경로 지정
      o: bind
