version: "3.9"

services:
  registry:
    image: registry:2.7
    container_name: registry
    restart: always
    ports:
      - "5555:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_AUTH: "htpasswd"
      REGISTRY_AUTH_HTPASSWD_REALM: "lhysin's Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"
    volumes:
      - /volume1/docker/registry:/var/lib/registry
      - /volume1/docker/registry/auth:/auth

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry_ui
    restart: always
    ports:
      - "5556:80"
    environment:
      REGISTRY_SECURED: true
      NGINX_PROXY_PASS_URL: ${NGINX_PROXY_PASS_URL}
    depends_on:
      - registry