version: "3.9"

services:
  registry:
    image: registry:2.7
    container_name: registry
    restart: always
    ports:
      - "5555:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_AUTH: "htpasswd"
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
    volumes:
      - registry_data:/var/lib/registry
      - registry_auth:/auth

  portus:
    image: opensuse/portus:head
    container_name: portus
    restart: always
    ports:
      - "5556:3000"  # Portus 웹 UI
    environment:
      PORTUS_MACHINE_FQDN: "localhost:5556"
      PORTUS_DB_PASSWORD: "your_db_password"
      PORTUS_DB_USERNAME: "portus"
      PORTUS_DB_HOST: "portus_db"
      PORTUS_SECRET_KEY_BASE: "long_secret_key_here"
    depends_on:
      - registry
      - portus_db

  portus_db:
    image: mariadb:10.5
    container_name: portus_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "portus"
      MYSQL_USER: "portus"
      MYSQL_PASSWORD: "your_db_password"
    volumes:
      - portus_db_data:/var/lib/mysql

volumes:
  registry_data:
    driver: local
    driver_opts:
      type: none
      device: /volume1/docker/registry
      o: bind
  registry_auth:
    driver: local
    driver_opts:
      type: none
      device: /volume1/docker/registry/auth
      o: bind
  portus_db_data:
    driver: local
    driver_opts:
      type: none
      device: /volume1/docker/registry/portus
      o: bind
