version: "3.9"

services:
  registry:
    image: registry:2.7
    container_name: registry
    restart: always
    ports:
      - "5555:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_AUTH: "htpasswd"
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
    volumes:
      - registry_data:/var/lib/registry
      - registry_auth:/auth

volumes:
  registry_data:
    driver: local
    driver_opts:
      type: none
      device: /volume1/docker/registry
      o: bind
  registry_auth:
    driver: local
    driver_opts:
      type: none
      device: /volume1/docker/registry/auth
      o: bind