version: "3.9"

services:
  server:
    image: docker.gitea.com/gitea:1.24.5
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - gitea_data:/data  # named volume 사용
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"

volumes:
  gitea_data:
    driver: local
    driver_opts:
      type: none
      device: /volume1/docker/gitea  # 호스트 경로 지정
      o: bind