version: "3.9"

networks:
  gitea:
    external: false

services:
  server:
    image: docker.gitea.com/gitea:1.24.5
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__SECURITY__ALLOWED_DOMAINS=github.com,gitlab.com
      - GITEA__SECURITY__ALLOW_LOCALNETWORKS=true
    restart: always
    networks:
      - gitea
    volumes:
      - /volume1/docker/gitea:/data
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"