version: '3.9'

services:
  gitlab:
    image: gitlab/gitlab-ce:18.3.1-ce.0
    container_name: gitlab
    restart: always
    hostname: "${GITLAB_HOSTNAME}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        nginx['listen_https'] = false
        gitlab_rails['registry_enabled'] = true
        registry_external_url '${GITLAB_REGISTRY_URL}'
    ports:
      - "2280:80"
      - "25050:5050"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    shm_size: '256m'

volumes:
  gitlab_config:
    driver: local
    driver_opts:
      type: none
      device: /volume1/docker/gitlab/config
      o: bind
  gitlab_logs:
    driver: local
    driver_opts:
      type: none
      device: /volume1/docker/gitlab/logs
      o: bind
  gitlab_data:
    driver: local
    driver_opts:
      type: none
      device: /volume1/docker/gitlab/data
      o: bind