version: '3'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566-4599:4566-4599"
      - "8080:8080"
    environment:
      SERVICES: "sqs,sns,s3,dynamodb,lambda,apigateway,cloudwatch,cloudformation"
      DEBUG: "1"
      DATA_DIR: "/tmp/localstack/data"
        #volumes:
      #- "./.localstack:/tmp/localstack"
      #command: "start --host 0.0.0.0"
