version: '3.3'
services:
  portainer:
    ports:
      - '9000:9000'
    container_name: portainer
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/app/portainer:/data'
    image: portainer/portainer