version: '3.9'

services:
  traefik:
    image: traefik:v2.10
    environment:
      - {ENVIRONMENT}
    command:
      # Docker Provider
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-public"
      - "--providers.docker.watch=true"
      
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      
      # ACME (Let's Encrypt)
      - "--certificatesResolvers.le.acme.dnsChallenge.provider=duckdns"
      - "--certificatesResolvers.le.acme.dnsChallenge.delayBeforeCheck=60"
      - "--certificatesResolvers.le.acme.dnsChallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
      - "--certificatesResolvers.le.acme.email={LE_EMAIL}"
      - "--certificatesResolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesResolvers.le.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
      
      # Logging
      - "--log.level=DEBUG"
      - "--accesslog=true"
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
    networks:
      - traefik-public
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.75"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

networks:
  traefik-public:
    external: true

volumes:
  traefik_letsencrypt:



# docker network create --driver=overlay --attachable traefik-public

# 인증서 레졸버 이름
#CERT_RESOLVER=blah

# Let's Encrypt 이메일
#LE_EMAIL=blah@gmail.com

# 서비스 도메인
#DOMAIN=blah.ddns.net

# mkdir -p traefik-letsencrypt
# touch traefik-letsencrypt/acme.json
# chmod 600 traefik-letsencrypt/acme.json