version: '3.3'
services:
  teamcity-server:
    container_name: teamcity-server
    volumes:
      - '/app/teamcity-server/datadir:/data/teamcity_server/datadir'
      - '/app/teamcity-server/logs:/opt/teamcity/logs'
    ports:
      - '8111:8111'
    image: 'vlrpi/teamcity-server:ubuntu-xenial-2021.1'
  teamcity-agent-1:
    container_name: teamcity-agent-1
    volumes:
      - '/app/teamcity-agent-1:/data/teamcity_agent/conf'
      - '/var/run/docker.sock:/var/run/docker.sock'
    privileged: true
    environment:
      - AGENT_NAME="oci-arm4c-teamcity-agent"
      - DOCKER_IN_DOCKER="start"
      - SERVER_URL="http://144.24.91.88:8111"/'
    image: 'vlrpi/teamcity-agent-arm64v8:ubuntu-xenial-2021.1'
  teamcity-agent-2:
    container_name: teamcity-agent-2
    volumes:
      - '/app/teamcity-agent-2:/data/teamcity_agent/conf'
      - '/var/run/docker.sock:/var/run/docker.sock'
    privileged: true
    environment:
      - AGENT_NAME="oci-arm4c-teamcity-agent"
      - DOCKER_IN_DOCKER="start"
      - SERVER_URL="http://144.24.91.88:8111"/'
    image: 'vlrpi/teamcity-agent-arm64v8:ubuntu-xenial-2021.1'
  teamcity-agent-3:
    container_name: teamcity-agent-3
    volumes:
      - '/app/teamcity-agent-3:/data/teamcity_agent/conf'
      - '/var/run/docker.sock:/var/run/docker.sock'
    privileged: true
    environment:
      - AGENT_NAME="oci-arm4c-teamcity-agent"
      - DOCKER_IN_DOCKER="start"
      - SERVER_URL="http://144.24.91.88:8111"/'
    image: 'vlrpi/teamcity-agent-arm64v8:ubuntu-xenial-2021.1'