version: '3.3'
services:
  teamcity-server:
    container_name: teamcity-server
    volumes:
      - '/app/teamcity-server/datadir:/data/teamcity_server/datadir'
      - '/app/teamcity-server/logs:/opt/teamcity/logs'
    ports:
      - '8111:8111'
    image: 'vlrpi/teamcity-server:ubuntu-xenial-2021.1'