version: '3.3'
services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config:/etc/prometheus
      - prometheus:/prometheus
    ports:
      - 9090:9090
    restart: always
    networks:
      - loki
    command:
      --web.enable-lifecycle
      --config.file="/etc/prometheus/prometheus-config.yml"
      #--web.listen-address="127.0.0.1:9090"
      #--web.route-prefix="prometheus"
      #--web.external-url="http://144.24.91.88:9000/prometheus"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    restart: always
    networks:
      - loki
    environment:
      GF_SERVER_DOMAIN: 144.24.91.88:3000
      GF_SERVER_ROOT_URL: "http://144.24.91.88:3000/grafana"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"

  loki:
    image: grafana/loki
    container_name: loki
    volumes:
      - ./config:/etc/loki
      - loki:/loki
    ports:
      - 3100:3100
    command:
      - '--config.file=/etc/loki/loki-config.yml'
    restart: always
    networks:
      - loki

volumes:
  prometheus:
  grafana:
  loki:

networks:
  loki:
