version: '3.7'
services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /app/prometheus/config:/etc/prometheus
      - /app/prometheus/volume:/prometheus
    ports:
      - 9090:9090
    command: # web.enalbe-lifecycle은 api 재시작없이 설정파일들을 reload 할 수 있게 해줌
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
