version: '3.3'

services:

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: backoffice
      MYSQL_DATABASE: backoffice
      MYSQL_USER: backoffice
      MYSQL_PASSWORD: backoffice
    ports:
      - 3306:3306

  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: imt
      MARIADB_DATABASE: imt
      MARIADB_USER: imt
      MARIADB_PASSWORD: imt
    ports:
      - 3305:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 3080:8080
