version: '3.3'

services:

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: backoffice
      MYSQL_DATABASE: backoffice
      MYSQL_USER: backoffice
      MYSQL_PASSWORD: backoffice
    ports:
      - 3306:3306

  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: maria
      MARIADB_DATABASE: maria
      MARIADB_USER: maria
      MARIADB_PASSWORD: maria
    ports:
      - 3305:3306
    volumes:
      - /app/mariadb:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 3080:8080
