version: '3.3'

services:

  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: cws
      MARIADB_DATABASE: cws
      MARIADB_USER: cws
      MARIADB_PASSWORD: cws
    ports:
      - 3307:3306