version: '3.3'

services:

  mariadb:
    image: mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: backoffice
      MARIADB_DATABASE: backoffice
      MARIADB_USER: backoffice
      MARIADB_PASSWORD: backoffice
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 3080:8080
