version: '3.3'

services:

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: backoffice
      MYSQL_DATABASE: backoffice
      MYSQL_USER: backoffice
      MYSQL_PASSWORD: backoffice
    ports:
      - 3306:3306