global:
  scrape_interval:     15s # 15초마다 매트릭을 수집한다. 기본은 1분.
  evaluation_interval: 15s # 15초마다 규칙을 평가한다. 기본은 1분.

  # 외부 시스템에 표시할 이 서버의 레이블
  external_labels:
      monitor: 'cws-monitor'

# 규칙을 로딩하고 'evaluation_interval' 설정에 따라 정기적으로 평가한다.
rule_files:
  # - "first.rules"
  # - "second.rules"

# 매트릭을 수집할 엔드포인드로 여기선 Prometheus 서버 자신을 가리킨다.
scrape_configs:
  # 이 설정에서 수집한 타임시리즈에 `job=<job_name>`으로 잡의 이름을 설정한다.
  - job_name: 'item-apiserver'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    static_configs:
      - targets: ['144.24.91.88:8880']
  - job_name: 'router-server'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    static_configs:
      - targets: ['144.24.91.88:8980']
