version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=9080
    volumes:
      - /path/to/appdata/config:/config
      - /path/to/downloads:/app/qbittorrent/downloads
    ports:
      - 9080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped