version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - WEBUI_PORT=9080
    volumes:
      - /app/qbittorrent/config:/config
      - /app/qbittorrent/downloads:/downloads
    ports:
      - 9080:9080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped