# arm64
version: '3.3'
services:
  gitlab-ce-arm64v8:
    restart: always
    container_name: gitlab-ce
    privileged: true
    ports:
      - '8180:80'
    hostname: 144.24.91.88
    environment:
      - GITLAB_OMNIBUS_CONFIG="nginx['redirect_http_to_https'] = true ";
    volumes:
      - '/app/gitlab-ce/conf:/etc/gitlab:z'
      - '/app/gitlab-ce/logs:/var/log/gitlab:z'
      - '/app/gitlab-ce/data:/var/opt/gitlab:z'
    image: 'yrzr/gitlab-ce-arm64v8:latest'